// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Error: typeof import('./src/components/Error.vue')['default'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    IconMdiAirplaneSearch: typeof import('~icons/mdi/airplane-search')['default'];
    IconSvgDaKa: typeof import('~icons/svg/da-ka')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    VanButton: typeof import('vant/es')['Button'];
  }
}
