// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Error: typeof import('./src/components/Error.vue')['default'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    IconMdiAirplaneSearch: typeof import('~icons/mdi/airplane-search')['default'];
    IconSvgDaKa: typeof import('~icons/svg/da-ka')['default'];
    VanButton: typeof import('vant/es')['Button'];
  }
}

export {};
